// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_RestricaoVideos.Context;

#nullable disable

namespace Project_RestricaoVideos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Project_RestricaoVideos.Models.Restricao", b =>
                {
                    b.Property<int>("retricaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("retricaoId"), 1L, 1);

                    b.Property<string>("restricaoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("retricaoId");

                    b.ToTable("Restricoes");
                });

            modelBuilder.Entity("Project_RestricaoVideos.Models.Video", b =>
                {
                    b.Property<int>("videosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("videosId"), 1L, 1);

                    b.Property<int>("restricaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("videoData")
                        .HasColumnType("datetime2");

                    b.Property<string>("videoDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("videosId");

                    b.HasIndex("restricaoId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Project_RestricaoVideos.Models.Video", b =>
                {
                    b.HasOne("Project_RestricaoVideos.Models.Restricao", "Restricao")
                        .WithMany("Videos")
                        .HasForeignKey("restricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restricao");
                });

            modelBuilder.Entity("Project_RestricaoVideos.Models.Restricao", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
